Home work 5 for fix
Nzimnevich/My_Recipes_2 pull request #5
Opened 2022-01-19 12:32 UTC by Nzimnevich

2022-01-28 20:27 UTC, Nzimnevich commented on app/src/main/res/layout/activity_filter.xml
> +<!--    <com.google.android.material.divider.MaterialDivider-->
оставила закоменченными, т.к.  для них нужна alpha версия, а alpha версия почему-то не дружит с чек-боксами, начинает на них ругаться

2022-01-29 09:24 UTC, MValuyskiy commented on app/src/main/res/layout/activity_filter.xml
> +<!--    <com.google.android.material.divider.MaterialDivider-->
Для разделителя можно еще сделать так:
Просто создать View с высотой 1 dp и серым цветом

2022-01-29 09:30 UTC, AndroidStudentClub commented on app/src/main/res/layout/activity_filter.xml
> +<!--    <com.google.android.material.divider.MaterialDivider-->
Это можно сделать добавив View

2022-01-29 09:32 UTC, AndroidStudentClub commented on app/src/main/res/layout/activity_filter.xml
> +<!--    <com.google.android.material.divider.MaterialDivider-->
Например
<View
    android:background="@color/colorPrimary"
    android:layout_width="match_parent"
    android:layout_height="1dp"/>

2022-01-29 10:01 UTC, AndroidStudentClub requested changes
Проверил

2022-01-29 10:01 UTC, AndroidStudentClub commented on app/src/main/java/com/example/myrecipes/FullRecipeActivity.kt
> +    private val typeOfMealsTv by lazy { binding.typeOfMealsTv }
Так как уже есть viewBinding то это лишнее можно сразу использовать  binding.typeOfMealsTv И так далее

2022-01-29 10:01 UTC, AndroidStudentClub commented on app/src/main/java/com/example/myrecipes/FullRecipeActivity.kt
> +        timeTV.setText(recipeFirst.timeToCook.toString() + getString(R.string.minutes)) //тут захардкоженные значения, как-то можно вместо этого plurals?
Чтобы использовать plurals нужно использовать метод getQuantityString
Для этого нужно описать строки
```
<plurals name="minutes">
    <item quantity="one">%d минута</item>
    <item quantity="other">%d минут</item>
</plurals>
Где %d - это placeholder вместо него будет подставляться число

2022-01-29 10:01 UTC, AndroidStudentClub commented on app/src/main/java/com/example/myrecipes/FullRecipeActivity.kt
> +        timeTV.setText(recipeFirst.timeToCook.toString() + getString(R.string.minutes)) //тут захардкоженные значения, как-то можно вместо этого plurals?
А потом
```
resources.getQuantityString(
    R.plurals.minutes, //plural from strings.xml file
    size, //число минут
    size, //var arg - first parameter
    allItemCount //var arg - second parameter
)
```

2022-01-29 10:01 UTC, AndroidStudentClub commented on app/src/main/java/com/example/myrecipes/FullRecipeActivity.kt
> +        timeTV.setText(recipeFirst.timeToCook.toString() + getString(R.string.minutes)) //тут захардкоженные значения, как-то можно вместо этого plurals?
https://stackoverflow.com/questions/34393271/android-plural-strings-with-multiple-parameters

2022-01-29 10:01 UTC, AndroidStudentClub commented on app/src/main/java/com/example/myrecipes/FullRecipeActivity.kt
> +        countOfCalTv.setText(recipeFirst.calories.toString() +getString(R.string.calories)) //тут захардкоженные значения, как-то можно вместо этого plurals?
можно вместо setText просто text

2022-01-29 10:01 UTC, AndroidStudentClub commented on app/src/main/java/com/example/myrecipes/FullRecipeActivity.kt
> +        firstStepTv.setText(recipeFirst.listOfSteps.get(0))//тут захардкоженные шаги
Тут можно было бы через foreach динамически программно создавать TextView, чтобы не писать get(0) а то если шагов будет 100 - то будет долго писать

2022-01-29 10:01 UTC, AndroidStudentClub commented on app/src/main/java/com/example/myrecipes/RegistrationActivity.kt
> +    private val emailTiet: TextInputEditText by lazy { binding.emailTiet }
Тоже уже лишнее, так как есть viewBinding

2022-01-29 10:01 UTC, AndroidStudentClub commented on app/src/main/java/com/example/myrecipes/RegistrationActivity.kt
> +    private val emailTiet: TextInputEditText by lazy { binding.emailTiet }
Можно теперь сразу использовать  binding.emailTiet

2022-01-29 10:01 UTC, AndroidStudentClub commented on app/src/main/java/com/example/myrecipes/RegistrationActivity.kt
>                  R.plurals.plurals_for_count_of_characters,
Вот тут же plurals используешь - можно точно так же и в деталях рецепта

2022-01-29 10:01 UTC, AndroidStudentClub commented on app/src/main/java/com/example/myrecipes/ui/CustomBottomSheetFragment.kt
> +            val intent = Intent(context, MainActivity::class.java)
Не, чтобы скрыть bottom sheet dialog достаточно вызвать this.dismiss()

2022-01-29 10:01 UTC, AndroidStudentClub commented on app/src/main/java/com/example/myrecipes/ui/CustomBottomSheetFragment.kt
> +            val intent = Intent(context, MainActivity::class.java)
Еще тут не хватает обработки нажатия на Chips. По идее при нажатии на них мы должны отправлять объект с данными которые выбрал пользователь. Это можно сделать через FragmentResultListener

2022-01-29 10:01 UTC, AndroidStudentClub commented on app/src/main/java/com/example/myrecipes/ui/CustomBottomSheetFragment.kt
> +            val intent = Intent(context, MainActivity::class.java)
Например
```
chipGroup.setOnCheckedChangeListener { group, checkedId ->
    var data: SelectedDataHolder? = null
    when (checkedId) {
        R.id.ChoiceA -> data = SelectedDataHolder("ChoiceA")
        R.id.ChoiceB -> data = SelectedDataHolder("ChoiceB")
        R.id.ChoiceC -> data = SelectedDataHolder("ChoiceC")
    }
    // Use the Kotlin extension in the fragment-ktx artifact
    setFragmentResult("filterChanged", bundleOf("bundleKey" to data))
}
```

2022-01-29 10:01 UTC, AndroidStudentClub commented on app/src/main/java/com/example/myrecipes/ui/CustomBottomSheetFragment.kt
> +            val intent = Intent(context, MainActivity::class.java)
Но для этого нужно еще там где мы запускаем данные диалог тоже сделать setFragmentListener

2022-01-29 10:01 UTC, AndroidStudentClub commented on app/src/main/java/com/example/myrecipes/ui/search/SearchFragment.kt
> +                CustomBottomSheetFragment.newInstance()
Сейчас диалог показывается, но нет обработки выбора фильтров. Чтобы получать еще результат того, что выбрал пользователь, можно сделать так:
```
childFragmentManager.setFragmentResultListener(
    "filterChanged",
    viewLifecycleOwner
) { key, bundle ->
    val result: SelectedDataHolder =
        bundle.getSerializable("bundleKey") as SelectedDataHolder

    // Do something with the result

    Log.d("HomeFragment", result.checkedChip)
    textView.setText(result.checkedChip)
}
```

2022-01-29 10:01 UTC, AndroidStudentClub commented on app/src/main/res/layout/activity_filter.xml
> +<!--    <com.google.android.material.divider.MaterialDivider-->
Можно так
```
<View
    android:background="@color/colorPrimary"
    android:layout_width="match_parent"
    android:layout_height="1dp"/>
```

2022-01-29 10:01 UTC, AndroidStudentClub commented on app/src/main/res/layout/search_fragment.xml
> +            android:layout_marginLeft="65dp"
Слишком большой отступ, можно 16 dp сделать - а то так верстка едет и карточка не помещается по ширине

2022-02-01 17:16 UTC, Nzimnevich commented on app/src/main/res/layout/search_fragment.xml
> +            android:layout_marginLeft="65dp"
поправила, но выглядит пустовато справа 
![image](https://user-images.githubusercontent.com/71277509/152017291-07d1383e-0ae8-4d9f-95b0-b8a4d8634f8d.png)

2022-02-02 13:52 UTC, Nzimnevich commented on app/src/main/java/com/example/myrecipes/FullRecipeActivity.kt
> +    private val typeOfMealsTv by lazy { binding.typeOfMealsTv }
если я использую binding.typeOfMealsTv, то мне вылетает ошибка : lateinit property binding has not been initialized

2022-02-02 13:53 UTC, Nzimnevich commented on app/src/main/java/com/example/myrecipes/ui/CustomBottomSheetFragment.kt
> +            val intent = Intent(context, MainActivity::class.java)
Выполню это в рамках дз 6-7

2022-02-11 08:54 UTC, merged